### ISSUE TITLE
json to CSV conversion is failing

### ISSUE THREAD

**Issue by prakdutt** [opendevl/Json2Flat#19]
Dear Sir

I am trying to convert a json data getting from a REST URL into URL. The issue which I am facing is that, first time when I am calling my program(fresh execution), csv file is generating successfully. On the same session, if I call the method of generate csv file from the json data, it is throwing the below error:

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 420 path $[8].desig
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at com.github.opendevl.JFlat.json2Sheet(JFlat.java:186)
	at com.github.opendevl.cdvprocess.TSheetOperation.transformJsonToCSVAndSaveInHDFS(TSheetOperation.java:39)
	at org.ciscocdv.javarest.resources.CDVDataIntegrationSaveResources.getSavedResourceInHDFS(CDVDataIntegrationSaveResources.java:36)
	at org.ciscocdv.javarest.restcdvdlppkg.CDVWebServiceOperations.saveDataIntegrationOutputInHDFS(CDVWebServiceOperations.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:301)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 420 path $[8].desig
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 51 more

I am running behind of time to solve this issue. Please suggest some way to solve this.
Thanks in advance.

**Comment by opendevl** [comment]
@prakdutt Sorry for the late reply. But can you please give the REST URL so that I can have a look at the json.

**Comment by prakdutt** [comment]
Hello Sir

Thanks a lot for your response. Because of certain security concern, I can't share the REST url but find the output in json format which is coming on the REST call in below:
-------------------------------------------------------------------------------------------------

{"exarcntrpbnWSuser23.exarcntrpbnWSuser23Response":{"exarcntrpbnWSuser23.exarcntrpbnWSuser23Output":{"exarcntrpbnWSuser23.row":[{"exarcntrpbnWSuser23.id":"1","exarcntrpbnWSuser23.name":"prakash","exarcntrpbnWSuser23.grade":-12,"exarcntrpbnWSuser23.desig":"developer"},{"exarcntrpbnWSuser23.id":"10","exarcntrpbnWSuser23.name":"Name2","exarcntrpbnWSuser23.grade":7333,"exarcntrpbnWSuser23.desig":"ComputerSo"},{"exarcntrpbnWSuser23.id":"11","exarcntrpbnWSuser23.name":"Name3","exarcntrpbnWSuser23.grade":-7333,"exarcntrpbnWSuser23.desig":"Informatio"},{"exarcntrpbnWSuser23.id":"12","exarcntrpbnWSuser23.name":"Name4","exarcntrpbnWSuser23.grade":-7,"exarcntrpbnWSuser23.desig":"Civil"},{"exarcntrpbnWSuser23.id":"13","exarcntrpbnWSuser23.name":"Name5","exarcntrpbnWSuser23.grade":37,"exarcntrpbnWSuser23.desig":"Medical"},{"exarcntrpbnWSuser23.id":"2","exarcntrpbnWSuser23.name":"Ming","exarcntrpbnWSuser23.grade":-155,"exarcntrpbnWSuser23.desig":"IT"},{"exarcntrpbnWSuser23.id":"3","exarcntrpbnWSuser23.name":"Eswara","exarcntrpbnWSuser23.grade":400,"exarcntrpbnWSuser23.desig":null},{"exarcntrpbnWSuser23.id":"33","exarcntrpbnWSuser23.name":"Name1","exarcntrpbnWSuser23.grade":7333,"exarcntrpbnWSuser23.desig":null},{"exarcntrpbnWSuser23.id":"4","exarcntrpbnWSuser23.name":"John","exarcntrpbnWSuser23.grade":100,"exarcntrpbnWSuser23.desig":"Compiler D"},{"exarcntrpbnWSuser23.id":"5","exarcntrpbnWSuser23.name":"Xin","exarcntrpbnWSuser23.grade":399,"exarcntrpbnWSuser23.desig":"AI"},{"exarcntrpbnWSuser23.id":"6","exarcntrpbnWSuser23.name":"Xiaan","exarcntrpbnWSuser23.grade":-399,"exarcntrpbnWSuser23.desig":null},{"exarcntrpbnWSuser23.id":"7","exarcntrpbnWSuser23.name":"Zhang","exarcntrpbnWSuser23.grade":-22,"exarcntrpbnWSuser23.desig":"Mechanical"},{"exarcntrpbnWSuser23.id":"8","exarcntrpbnWSuser23.name":"AnotherNam","exarcntrpbnWSuser23.grade":2000,"exarcntrpbnWSuser23.desig":"Electronic"},{"exarcntrpbnWSuser23.id":"9","exarcntrpbnWSuser23.name":"RealName","exarcntrpbnWSuser23.grade":333,"exarcntrpbnWSuser23.desig":"Elcectrica"}]}}}

------------------------------------------------------------------------------------------
In CSV file, the fields name should be id, name, grade, desig. These fields are dynamic.

Thanks a lot.

**Comment by opendevl** [comment]
@prakdutt  Again sorry for the late reply. I think we are getting the id, name, grade, desig fields.
Below is the table generated from your json. From from the header we get **exarcntrpbnWSuser23.id, exarcntrpbnWSuser23.name, exarcntrpbnWSuser23.grade, exarcntrpbnWSuser23.desig** at the **end** of each header. For a quick view you can go to [**Json2Flat Evaluator**](https://j2flateval.herokuapp.com/). Hope this helps.

| exarcntrpbnWSuser23.exarcntrpbnWSuser23Response_exarcntrpbnWSuser23.exarcntrpbnWSuser23Output_exarcntrpbnWSuser23.row_exarcntrpbnWSuser23.id | exarcntrpbnWSuser23.exarcntrpbnWSuser23Response_exarcntrpbnWSuser23.exarcntrpbnWSuser23Output_exarcntrpbnWSuser23.row_exarcntrpbnWSuser23.name | exarcntrpbnWSuser23.exarcntrpbnWSuser23Response_exarcntrpbnWSuser23.exarcntrpbnWSuser23Output_exarcntrpbnWSuser23.row_exarcntrpbnWSuser23.grade | exarcntrpbnWSuser23.exarcntrpbnWSuser23Response_exarcntrpbnWSuser23.exarcntrpbnWSuser23Output_exarcntrpbnWSuser23.row_exarcntrpbnWSuser23.desi | 
|----------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------| 
| "1"                                                                                                                                          | "prakash"                                                                                                                                      | -12.0                                                                                                                                           | "developer                                                                                                                                     | 
| "10"                                                                                                                                         | "Name2"                                                                                                                                        | 7333.0                                                                                                                                          | "ComputerSo                                                                                                                                    | 
| "11"                                                                                                                                         | "Name3"                                                                                                                                        | -7333.0                                                                                                                                         | "Informatio                                                                                                                                    | 
| "12"                                                                                                                                         | "Name4"                                                                                                                                        | -7.0                                                                                                                                            | "Civil                                                                                                                                         | 
| "13"                                                                                                                                         | "Name5"                                                                                                                                        | 37.0                                                                                                                                            | "Medical                                                                                                                                       | 
| "2"                                                                                                                                          | "Ming"                                                                                                                                         | -155.0                                                                                                                                          | "IT                                                                                                                                            | 
| "3"                                                                                                                                          | "Eswara"                                                                                                                                       | 400.0                                                                                                                                           |                                                                                                                                                | 
| "33"                                                                                                                                         | "Name1"                                                                                                                                        | 7333.0                                                                                                                                          |                                                                                                                                                | 
| "4"                                                                                                                                          | "John"                                                                                                                                         | 100.0                                                                                                                                           | "Compiler D                                                                                                                                    | 
| "5"                                                                                                                                          | "Xin"                                                                                                                                          | 399.0                                                                                                                                           | "AI                                                                                                                                            | 
| "6"                                                                                                                                          | "Xiaan"                                                                                                                                        | -399.0                                                                                                                                          |                                                                                                                                                | 
| "7"                                                                                                                                          | "Zhang"                                                                                                                                        | -22.0                                                                                                                                           | "Mechanical                                                                                                                                    | 
| "8"                                                                                                                                          | "AnotherNam"                                                                                                                                   | 2000.0                                                                                                                                          | "Electronic                                                                                                                                    | 
| "9"                                                                                                                                          | "RealName"                                                                                                                                     | 333.0                                                                                                                                           | "Elcectrica                                                                                                                                    |

**Comment by prakdutt** [comment]
Hi
Thanks a lot for your help and support. I am able to get the output. I have few more questions as described below:
1) The process is running successfully but sometimes the error is occurring as described in above. I like to keep the header field name as "id" beside of "exarcntrpbnWSuser23.exarcntrpbnWSuser23Response_exarcntrpbnWSuser23.exarcntrpbnWSuser23Output_exarcntrpbnWSuser23.row_exarcntrpbnWSuser23.id". I am asking this question as because, I need to write the csv file directly to HDFS. I don't have any mediator memory where I can save the file physically and change the header. So, it is possible to change the header in runtime as I mentioned in above?

2) Out of the box question, can I mention the fields name which I like to extract in the CSV file from the REST URL?

Thanks a lot.
Regards

**Comment by opendevl** [comment]
@prakdutt Both can be achived.

1. Yes, you can change the header in runtime. You can call **getJsonAsSheet()** which returns a **List<Object[]>**. The 1st element in the list contains the header and you can change as you wish. And the error may be because of something going wrong while creating the JSON.

2. Not sure about which REST URL you are talking. But if you have developed your own REST URL the you can send the the field names and change the headers after parsing the JSON doc and calling the function **getJsonAsSheet()** which in turn returns a **List<Object[]>**

**Comment by prakdutt** [comment]
Hello
Thanks a lot for your reply. Do you please help me to find a solution on  below issue:
Without terminating the program, if I execute the json2flat program again(2nd time), I am getting below error:

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonExcepti Unterminated object at line 1 column 420 path $[8].desig
        at com.google.gson.internal.Streams.parse(Streams.java:60)              
        at com.google.gson.JsonParser.parse(JsonParser.java:84)                 
        at com.google.gson.JsonParser.parse(JsonParser.java:59)                 
        at com.google.gson.JsonParser.parse(JsonParser.java:45)                 
        at org.ciscocdv.javarest.utilitypkg.jsonflat.JFlat.json2Sheet(JFlat.java9)
        at org.ciscocdv.javarest.utilitypkg.jsonflat.TSheetOperation.transformJsoCSVAndSaveInHDFS(TSheetOperation.java:43)
        at org.ciscocdv.javarest.resources.CDVDataIntegrationSaveResources.getSaResourceInHDFS(CDVDataIntegrationSaveResources.java:46)
        at org.ciscocdv.javarest.restcdvdlppkg.CDVWebServiceOperations.saveDataIgrationOutputInHDFS(CDVWebServiceOperations.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)          
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.a:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccesImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)                     
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMedInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchPr                                                                             ovider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDitcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethode.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHaathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourcassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHaathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequ(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequ(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequeWebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequeWebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponenava:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(Servlettainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(Servlettainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)         
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(AppltionFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFerChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(AppltionFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFerChain.java:208)
        at org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.ja301)
        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169) 
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(AppltionFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFerChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperVe.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextVe.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticaBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValjava:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav45)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttprocessor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(tractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoinava:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.a:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutorva:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThd.java:61)
        at java.lang.Thread.run(Thread.java:745)                                
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object atne 1 column 420 path $[8].desig
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)  
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)        
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)       
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        ... 51 more

If I terminate the program and restart again, the issue is not occurring. But without terminating the program, if I execute on same input data set again, above exception is showing. 

Please suggest me a way to solve this issue.

**Comment by prakdutt** [comment]
Dear Sir,

I observed that the below line is throwing exceptions as described above:
List<Object[]> json2csv = flatMe.json2Sheet().getJsonAsSheet();

And the Error message is : 
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 25
	at com.google.gson.internal.Streams.parse(Streams.java:56)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at org.ciscocdv.javarest.utilitypkg.jsonflat.JFlat.json2Sheet(JFlat.java:257)

And error messages is occurring from second time onwords of the executing. 
The scenario is like below:
1) I have my own java project(REST Webservices) which in deployed in the tomcat server. 
The Parameter of  my REST services is a URL which is giving me a JSON data. (This URL can only be used by authorized userid and password).  
2) I am able to get the json data in JFlat object any numbers of time. After getting the JSON data, when I am trying to use the below code,
List<Object[]> json2csv = flatMe.json2Sheet().getJsonAsSheet();
The above exception is started throwing the application. The error is not showing if I restart the tomcat again. 

Do you please help me to get some ideas to solve this error.
Thanks a lot.
Regards,
